### ISSUE TITLE
`strftime` is deprecated as of PHP 8.1

### ISSUE THREAD

**Issue by adamkiss** [johannschopplich/kirbylog#1]
You can see in the [PHP docs](https://www.php.net/manual/en/function.strftime.php), for instance.

Alternatives:

- I used `date()` in my config
- `DateTime::format`, or `date_format(date_create(), "format")`

Where:

- config
- documentation about config options

I can PR

**Comment by adamkiss** [comment]
After a brain freeze I realized, of course, that a difference between `date()` and `strftime()` is that `strftime` has denoted which elements are a date/time symbol, and everything else is just passed as is, while `date()` (and `DateTime::format`) interpret every character as a date/time formatter _unless_ escaped with a backslash.

I don't think that changes much.

**Comment by johannschopplich** [comment]
Thanks for the report! Fixed in https://github.com/johannschopplich/kirbylog/commit/82083fb092be53343c1d1d4262615db31b7e57dc.
I think `date` is enough, no need for a formatted local date. What do you think?

**Comment by adamkiss** [comment]
@johannschopplich I think `date()` is completely okay - the only difference is that you can't do stuff like `strftime('Weird-Name-%Y-%m-%d.log')` in one command/string, but I think that doesn't really matter.
